### ISSUE TITLE
Context menu on Tracks tab difficult to tap

### ISSUE THREAD

**Issue by rio-codes** [thibseisel/android-odeon#44]
The 3-dot context menu to the right of each track in the track tab is very difficult to tap without changing the position in the tracklist. I have tried multiple resolutions and still have the same issue. Trying to tap the dots quickly to add a track to a playlist usually results in scrolling down or up the tracklist rather than opening the menu.

![contextmenu](https://user-images.githubusercontent.com/791713/185469103-68078c8e-4a84-4bee-9389-a511f3864db4.jpeg)

I love this app! I am willing to contribute to development, I also have a feature I'd like to request/help implement.

**Comment by rio-codes** [comment]
I also wanted to add I am using a Pixel 4a running LineageOS 19.1 (Android 12) and have tried Display Size at Small, Default, Large, and Larger with the same issue.) Resolution is 1080x2340, 19:5:9 ratio.

**Comment by thibseisel** [comment]
Thanks for your feedback!
This menu button is definitely not easy to trigger because it is partially overlaid by the list's fast-scroller.
I have been refactoring the app a lot since the last release ; the issue has probably been solved when I removed the list's fast-scroller.

Regarding your feature request, you could open another issue to explain in details.
I'd also be glad to accept some contributions! Maybe I should add a contribution guide, so that we could agree on the same conventions.

**Comment by rio-codes** [comment]
Yes, the issue has been solved in this release! Thank you so much. My feature request was about native scrobbling to last.fm, but I did find [pScrobbler](https://github.com/kawaiiDango/pScrobbler) that integrates perfectly with Odeon so I don't really need it any more. I'll look into existing issues though to see if I can find anything to help with. :)
